name: sillysuitcase
display_name: SillySuitcase
description: A Flutter application built from scratch.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  

  # HTTP & API
  http: ^1.2.0

  # State Management (optional but recommended)
  provider: ^6.1.2

  # HTML Rendering (WordPress content)
  flutter_html: ^3.0.0

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.0


  


  # Add this line:
  shared_preferences: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # App Icon
  flutter_launcher_icons: ^0.13.1

  # Splash Screen
  flutter_native_splash: ^2.4.1

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/icon/sillysuitcase.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/sillysuitcase.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

 
